const categories = [
    {
        id: '1',
        name: 'Российская Премьер-Лига',
        items: [
            {id: '11', name: 'Локомотив', price: 1800, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/loko/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/loko/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/loko/3.jpg'},],
            },
            {id: '12', name: 'Зенит', price: 1800, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/zen/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/zen/2.jpg'},],
            },
            {id: '13', name: 'Спартак', price: 1500, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/spam/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/spam/2.jpg'},],
            },
            {id: '14', name: 'Краснодар', price: 1700, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/kra/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/kra/2.jpg'},],
            },
        ],
    },
    {
        id: '2',
        name: 'Английская Премьер-Лига',
        items: [
            {id: '21', name: 'Арсенал', price: 1500, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/ars/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/ars/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/ars/3.jpg'},],
            },
            {id: '22', name: 'Ливерпуль', price: 2000, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/liv/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/liv/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/liv/3.jpg'},],
            },
            {id: '23', name: 'Челси', price: 2500, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/che/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/che/2.jpg'},
                    {name: 'резервная',
                        pic:'img/kits/che/3.jpg'},],
            },
            {id: '24', name: 'Манчестер Сити', price: 3200, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/mancity/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/mancity/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/mancity/3.jpg'},],
            },
        ],
    },
    {
        id: '3',
        name: 'Бундеслига',
        items: [
            {id: '31', name: 'Бавария', price: 2000, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/baym/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/baym/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/baym/3.jpg'},],
            },
            {id: '32', name: 'Боруссия', price: 2500, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/bor/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/bor/2.jpg'},],
            },
            {id: '33', name: 'Лейпциг', price: 1500, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/leip/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/leip/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/leip/3.jpg'},],
            },
        ],
    },
    {
        id: '4',
        name: 'Серия А',
        items: [
            {id: '41', name: 'Ювентус', price: 2700, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/juve/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/juve/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/juve/3.jpg'},],
            },
            {id: '42', name: 'Аталанта', price: 1500, type: [
                    {name: 'домашняя',
                        pic:'img/kits/ata/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/ata/2.jpg'},],
            },
            {id: '43', name: 'Интер', price: 2300, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/int/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/int/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/int/3.jpg'},],
            },
            {id: '44', name: 'Милан', price: 2000, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/milan/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/milan/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/milan/3.jpg'},],
            },
            {id: '45', name: 'Парма', price: 2400, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/parma/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/parma/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/parma/3.jpg'},],
            },
        ],
    },
    {
        id: '5',
        name: 'Ла Лига',
        items: [
            {id: '51', name: 'Реал', price: 2000, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/rm/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/rm/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/rm/3.jpg'},],
            },
            {id: '52', name: 'Барселона', price: 2000, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/bar/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/bar/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/bar/3.jpg'},],
            },
            {id: '53', name: 'Валенсия', price: 2200, type: [
                    {name: 'домашняя',
                        pic: 'img/kits/val/1.jpg'},
                    {name: 'выездная',
                        pic: 'img/kits/val/2.jpg'},
                    {name: 'резервная',
                        pic: 'img/kits/val/3.jpg'},],
            },
        ],
    },
];